# -*- coding: utf-8 -*- 
class I18n():
    LANG = {
        "en":u"English (US)‎",
        "zh_CN":u"中文（简体）‎",
        "ja":u"日本語"
    }
    LOCALE = [
        ('aa_DJ',u'Qafar (Yabuuti)'),
        ('aa_ER',u'Qafar (Eretria)'),
        ('aa_ET',u'Qafar (Otobbia)'),
        ('af_NA',u'Afrikaans (Namibië)'),
        ('af_ZA',u'Afrikaans (Suid-Afrika)'),
        ('agq_CM',u'Aghem (Kàmàlûŋ)'),
        ('ak_GH',u'Akan (Gaana)'),
        ('am_ET',u'አማርኛ (ኢትዮጵያ)'),
        ('ar_AE',u'العربية (الإمارات العربية المتحدة)'),
        ('ar_BH',u'العربية (البحرين)'),
        ('ar_DJ',u'العربية (جيبوتي)'),
        ('ar_DZ',u'العربية (الجزائر)'),
        ('ar_EG',u'العربية (مصر)'),
        ('ar_EH',u'العربية (الصحراء الغربية)'),
        ('ar_ER',u'العربية (أريتريا)'),
        ('ar_IL',u'العربية (إسرائيل)'),
        ('ar_IQ',u'العربية (العراق)'),
        ('ar_JO',u'العربية (الأردن)'),
        ('ar_KM',u'العربية (جزر القمر)'),
        ('ar_KW',u'العربية (الكويت)'),
        ('ar_LB',u'العربية (لبنان)'),
        ('ar_LY',u'العربية (ليبيا)'),
        ('ar_MA',u'العربية (المغرب)'),
        ('ar_MR',u'العربية (موريتانيا)'),
        ('ar_OM',u'العربية (عُمان)'),
        ('ar_PS',u'العربية (فلسطين)'),
        ('ar_QA',u'العربية (قطر)'),
        ('ar_SA',u'العربية (المملكة العربية السعودية)'),
        ('ar_SD',u'العربية (السودان)'),
        ('ar_SO',u'العربية (الصومال)'),
        ('ar_SY',u'العربية (سوريا)'),
        ('ar_TD',u'العربية (تشاد)'),
        ('ar_TN',u'العربية (تونس)'),
        ('ar_YE',u'العربية (اليمن)'),
        ('as_IN',u'অসমীয়া (ভাৰত)'),
        ('asa_TZ',u'Kipare (Tadhania)'),
        ('ast_ES',u'asturianu (España)'),
        ('az_Cyrl_AZ',u'Азәрбајҹан (kiril, Азәрбајҹан)'),
        ('az_Latn_AZ',u'azərbaycanca (latın, Azərbaycan)'),
        ('bas_CM',u'Ɓàsàa (Kàmɛ̀rûn)'),
        ('be_BY',u'беларуская (Беларусь)'),
        ('bem_ZM',u'Ichibemba (Zambia)'),
        ('bez_TZ',u'Hibena (Hutanzania)'),
        ('bg_BG',u'български (България)'),
        ('bm_ML',u'bamanakan (Mali)'),
        ('bn_BD',u'বাংলা (বাংলাদেশ)'),
        ('bn_IN',u'বাংলা (ভারত)'),
        ('bo_CN',u'པོད་སྐད་ (རྒྱ་ནག)'),
        ('bo_IN',u'པོད་སྐད་ (རྒྱ་གར་)'),
        ('br_FR',u'brezhoneg (Frañs)'),
        ('brx_IN',u'बड़ो (भारत)'),
        ('bs_Cyrl_BA',u'босански (Ћирилица, Босна и Херцеговина)'),
        ('bs_Latn_BA',u'bosanski (latinica, Bosna i Hercegovina)'),
        ('byn_ER',u'ብሊን (ኤርትራ)'),
        ('ca_AD',u'català (Andorra)'),
        ('ca_ES',u'català (Espanya)'),
        ('cgg_UG',u'Rukiga (Uganda)'),
        ('chr_US',u'ᏣᎳᎩ (ᎠᎹᏰᏟ)'),
        ('cs_CZ',u'čeština (Česká republika)'),
        ('cy_GB',u'Cymraeg (y Deyrnas Unedig)'),
        ('da_DK',u'dansk (Danmark)'),
        ('dav_KE',u'Kitaita (Kenya)'),
        ('de_AT',u'Deutsch (Österreich)'),
        ('de_BE',u'Deutsch (Belgien)'),
        ('de_CH',u'Deutsch (Schweiz)'),
        ('de_DE',u'Deutsch (Deutschland)'),
        ('de_LI',u'Deutsch (Liechtenstein)'),
        ('de_LU',u'Deutsch (Luxemburg)'),
        ('dje_NE',u'Zarmaciine (Nižer)'),
        ('dua_CM',u'duálá (Cameroun)'),
        ('dyo_SN',u'joola (Senegal)'),
        ('dz_BT',u'རྫོང་ཁ (འབྲུག)'),
        ('ebu_KE',u'Kĩembu (Kenya)'),
        ('ee_GH',u'eʋegbe (Ghana nutome)'),
        ('ee_TG',u'eʋegbe (Togo nutome)'),
        ('el_CY',u'Ελληνικά (Κύπρος)'),
        ('el_GR',u'Ελληνικά (Ελλάδα)'),
        ('en_AG',u'English (Antigua and Barbuda)'),
        ('en_AS',u'English (American Samoa)'),
        ('en_AU',u'English (Australia)'),
        ('en_BB',u'English (Barbados)'),
        ('en_BE',u'English (Belgium)'),
        ('en_BM',u'English (Bermuda)'),
        ('en_BS',u'English (Bahamas)'),
        ('en_BW',u'English (Botswana)'),
        ('en_BZ',u'English (Belize)'),
        ('en_CA',u'English (Canada)'),
        ('en_CM',u'English (Cameroon)'),
        ('en_DM',u'English (Dominica)'),
        ('en_Dsrt_US',u'𐐀𐑍𐑊𐐮𐑇 (𐐔𐐯𐑆𐐲𐑉𐐯𐐻, 𐐏𐐭𐑌𐐴𐐻𐐲𐐼 𐐝𐐻𐐩𐐻𐑅)'),
        ('en_FM',u'English (Micronesia)'),
        ('en_GB',u'English (United Kingdom)'),
        ('en_GD',u'English (Grenada)'),
        ('en_GG',u'English (Guernsey)'),
        ('en_GH',u'English (Ghana)'),
        ('en_GI',u'English (Gibraltar)'),
        ('en_GM',u'English (Gambia)'),
        ('en_GU',u'English (Guam)'),
        ('en_GY',u'English (Guyana)'),
        ('en_HK',u'English (Hong Kong SAR China)'),
        ('en_IE',u'English (Ireland)'),
        ('en_IM',u'English (Isle of Man)'),
        ('en_IN',u'English (India)'),
        ('en_JE',u'English (Jersey)'),
        ('en_JM',u'English (Jamaica)'),
        ('en_KE',u'English (Kenya)'),
        ('en_KI',u'English (Kiribati)'),
        ('en_KN',u'English (Saint Kitts and Nevis)'),
        ('en_KY',u'English (Cayman Islands)'),
        ('en_LC',u'English (Saint Lucia)'),
        ('en_LR',u'English (Liberia)'),
        ('en_LS',u'English (Lesotho)'),
        ('en_MG',u'English (Madagascar)'),
        ('en_MH',u'English (Marshall Islands)'),
        ('en_MP',u'English (Northern Mariana Islands)'),
        ('en_MT',u'English (Malta)'),
        ('en_MU',u'English (Mauritius)'),
        ('en_MW',u'English (Malawi)'),
        ('en_NA',u'English (Namibia)'),
        ('en_NG',u'English (Nigeria)'),
        ('en_NZ',u'English (New Zealand)'),
        ('en_PG',u'English (Papua New Guinea)'),
        ('en_PH',u'English (Philippines)'),
        ('en_PK',u'English (Pakistan)'),
        ('en_PR',u'English (Puerto Rico)'),
        ('en_PW',u'English (Palau)'),
        ('en_SB',u'English (Solomon Islands)'),
        ('en_SC',u'English (Seychelles)'),
        ('en_SG',u'English (Singapore)'),
        ('en_SL',u'English (Sierra Leone)'),
        ('en_SS',u'English (South Sudan)'),
        ('en_SZ',u'English (Swaziland)'),
        ('en_TC',u'English (Turks and Caicos Islands)'),
        ('en_TO',u'English (Tonga)'),
        ('en_TT',u'English (Trinidad and Tobago)'),
        ('en_TZ',u'English (Tanzania)'),
        ('en_UG',u'English (Uganda)'),
        ('en_UM',u'English (U.S. Outlying Islands)'),
        ('en_US',u'English (United States)'),
        ('en_US_POSIX',u'English (United States, Computer)'),
        ('en_US_POSIX',u'English (United States, Computer)'),
        ('en_VC',u'English (Saint Vincent and the Grenadines)'),
        ('en_VG',u'English (British Virgin Islands)'),
        ('en_VI',u'English (U.S. Virgin Islands)'),
        ('en_VU',u'English (Vanuatu)'),
        ('en_WS',u'English (Samoa)'),
        ('en_ZA',u'English (South Africa)'),
        ('en_ZM',u'English (Zambia)'),
        ('en_ZW',u'English (Zimbabwe)'),
        ('es_AR',u'español (Argentina)'),
        ('es_BO',u'español (Bolivia)'),
        ('es_CL',u'español (Chile)'),
        ('es_CO',u'español (Colombia)'),
        ('es_CR',u'español (Costa Rica)'),
        ('es_CU',u'español (Cuba)'),
        ('es_DO',u'español (República Dominicana)'),
        ('es_EA',u'español (Ceuta y Melilla)'),
        ('es_EC',u'español (Ecuador)'),
        ('es_ES',u'español (España)'),
        ('es_GQ',u'español (Guinea Ecuatorial)'),
        ('es_GT',u'español (Guatemala)'),
        ('es_HN',u'español (Honduras)'),
        ('es_IC',u'español (Islas Canarias)'),
        ('es_MX',u'español (México)'),
        ('es_NI',u'español (Nicaragua)'),
        ('es_PA',u'español (Panamá)'),
        ('es_PE',u'español (Perú)'),
        ('es_PH',u'español (Filipinas)'),
        ('es_PR',u'español (Puerto Rico)'),
        ('es_PY',u'español (Paraguay)'),
        ('es_SV',u'español (El Salvador)'),
        ('es_US',u'español (Estados Unidos)'),
        ('es_UY',u'español (Uruguay)'),
        ('es_VE',u'español (Venezuela)'),
        ('et_EE',u'eesti (Eesti)'),
        ('eu_ES',u'euskara (Espainia)'),
        ('ewo_CM',u'ewondo (Kamərún)'),
        ('fa_AF',u'دری (افغانستان)'),
        ('fa_IR',u'فارسی (ایران)'),
        ('ff_SN',u'Pulaar (Senegaal)'),
        ('fi_FI',u'suomi (Suomi)'),
        ('fil_PH',u'Filipino (Pilipinas)'),
        ('fo_FO',u'føroyskt (Føroyar)'),
        ('fr_BE',u'français (Belgique)'),
        ('fr_BF',u'français (Burkina Faso)'),
        ('fr_BI',u'français (Burundi)'),
        ('fr_BJ',u'français (Bénin)'),
        ('fr_BL',u'français (Saint-Barthélémy)'),
        ('fr_CA',u'français (Canada)'),
        ('fr_CD',u'français (République démocratique du Congo)'),
        ('fr_CF',u'français (République centrafricaine)'),
        ('fr_CG',u'français (Congo-Brazzaville)'),
        ('fr_CH',u'français (Suisse)'),
        ('fr_CI',u'français (Côte d’Ivoire)'),
        ('fr_CM',u'français (Cameroun)'),
        ('fr_DJ',u'français (Djibouti)'),
        ('fr_DZ',u'français (Algérie)'),
        ('fr_FR',u'français (France)'),
        ('fr_GA',u'français (Gabon)'),
        ('fr_GF',u'français (Guyane française)'),
        ('fr_GN',u'français (Guinée)'),
        ('fr_GP',u'français (Guadeloupe)'),
        ('fr_GQ',u'français (Guinée équatoriale)'),
        ('fr_HT',u'français (Haïti)'),
        ('fr_KM',u'français (Comores)'),
        ('fr_LU',u'français (Luxembourg)'),
        ('fr_MA',u'français (Maroc)'),
        ('fr_MC',u'français (Monaco)'),
        ('fr_MF',u'français (Saint-Martin [partie française])'),
        ('fr_MG',u'français (Madagascar)'),
        ('fr_ML',u'français (Mali)'),
        ('fr_MQ',u'français (Martinique)'),
        ('fr_MR',u'français (Mauritanie)'),
        ('fr_MU',u'français (Maurice)'),
        ('fr_NC',u'français (Nouvelle-Calédonie)'),
        ('fr_NE',u'français (Niger)'),
        ('fr_PF',u'français (Polynésie française)'),
        ('fr_RE',u'français (Réunion)'),
        ('fr_RW',u'français (Rwanda)'),
        ('fr_SC',u'français (Seychelles)'),
        ('fr_SN',u'français (Sénégal)'),
        ('fr_SY',u'français (Syrie)'),
        ('fr_TD',u'français (Tchad)'),
        ('fr_TG',u'français (Togo)'),
        ('fr_TN',u'français (Tunisie)'),
        ('fr_VU',u'français (Vanuatu)'),
        ('fr_YT',u'français (Mayotte)'),
        ('fur_IT',u'furlan (Italie)'),
        ('ga_IE',u'Gaeilge (Éire)'),
        ('gd_GB',u'Gàidhlig (An Rìoghachd Aonaichte)'),
        ('gl_ES',u'galego (España)'),
        ('gsw_CH',u'Schwiizertüütsch (Schwiiz)'),
        ('gu_IN',u'ગુજરાતી (ભારત)'),
        ('guz_KE',u'Ekegusii (Kenya)'),
        ('gv_GB',u'Gaelg (Rywvaneth Unys)'),
        ('ha_Latn_GH',u'Hausa (Gana)'),
        ('ha_Latn_NE',u'Hausa (Nijar)'),
        ('ha_Latn_NG',u'Hausa (Najeriya)'),
        ('haw_US',u'ʻŌlelo Hawaiʻi (ʻAmelika Hui Pū ʻIa)'),
        ('he_IL',u'עברית (ישראל)'),
        ('hi_IN',u'हिन्दी (भारत)'),
        ('hr_BA',u'hrvatski (Bosna i Hercegovina)'),
        ('hr_HR',u'hrvatski (Hrvatska)'),
        ('hu_HU',u'magyar (Magyarország)'),
        ('hy_AM',u'հայերեն (Հայաստան)'),
        ('ia_FR',u'interlingua (Francia)'),
        ('id_ID',u'Bahasa Indonesia (Indonesia)'),
        ('ig_NG',u'Igbo (Nigeria)'),
        ('ii_CN',u'ꆈꌠꉙ (ꍏꇩ)'),
        ('is_IS',u'íslenska (Ísland)'),
        ('it_CH',u'italiano (Svizzera)'),
        ('it_IT',u'italiano (Italia)'),
        ('it_SM',u'italiano (San Marino)'),
        ('ja_JP',u'日本語 (日本)'),
        ('jmc_TZ',u'Kimachame (Tanzania)'),
        ('ka_GE',u'ქართული (საქართველო)'),
        ('kab_DZ',u'Taqbaylit (Lezzayer)'),
        ('kam_KE',u'Kikamba (Kenya)'),
        ('kde_TZ',u'Chimakonde (Tanzania)'),
        ('kea_CV',u'kabuverdianu (Kabu Verdi)'),
        ('khq_ML',u'Koyra ciini (Maali)'),
        ('ki_KE',u'Gikuyu (Kenya)'),
        ('kk_Cyrl_KZ',u'қазақ тілі (кириллица, Қазақстан)'),
        ('kkj_CM',u'kakɔ (Kamɛrun)'),
        ('kl_GL',u'kalaallisut (Kalaallit Nunaat)'),
        ('kln_KE',u'Kalenjin (Emetab Kenya)'),
        ('km_KH',u'ខ្មែរ (កម្ពុជា)'),
        ('kn_IN',u'ಕನ್ನಡ (ಭಾರತ)'),
        ('ko_KP',u'한국어 (조선 민주주의 인민 공화국)'),
        ('ko_KR',u'한국어 (대한민국)'),
        ('kok_IN',u'कोंकणी (भारत)'),
        ('ks_Arab_IN',u'کٲشُر (اَربی, ہِنٛدوستان)'),
        ('ksb_TZ',u'Kishambaa (Tanzania)'),
        ('ksf_CM',u'rikpa (kamɛrún)'),
        ('ksh_DE',u'Kölsch (Doütschland)'),
        ('kw_GB',u'kernewek (Rywvaneth Unys)'),
        ('ky_KG',u'Кыргыз (Кыргызстан)'),
        ('lag_TZ',u'Kɨlaangi (Taansanía)'),
        ('lg_UG',u'Luganda (Yuganda)'),
        ('ln_AO',u'lingála (Angóla)'),
        ('ln_CD',u'lingála (Repibiki demokratiki ya Kongó)'),
        ('ln_CF',u'lingála (Repibiki ya Afríka ya Káti)'),
        ('ln_CG',u'lingála (Kongo)'),
        ('lo_LA',u'ລາວ (ສ.ປ.ປ ລາວ)'),
        ('lt_LT',u'lietuvių (Lietuva)'),
        ('lu_CD',u'Tshiluba (Ditunga wa Kongu)'),
        ('luo_KE',u'Dholuo (Kenya)'),
        ('luy_KE',u'Luluhia (Kenya)'),
        ('lv_LV',u'latviešu (Latvija)'),
        ('mas_KE',u'Maa (Kenya)'),
        ('mas_TZ',u'Maa (Tansania)'),
        ('mer_KE',u'Kĩmĩrũ (Kenya)'),
        ('mfe_MU',u'kreol morisien (Moris)'),
        ('mg_MG',u'Malagasy (Madagasikara)'),
        ('mgh_MZ',u'Makua (Umozambiki)'),
        ('mgo_CM',u'metaʼ (Kamalun)'),
        ('mk_MK',u'македонски (Македонија)'),
        ('ml_IN',u'മലയാളം (ഇന്ത്യ)'),
        ('mn_Cyrl_MN',u'монгол (Кирил, Монгол)'),
        ('mr_IN',u'मराठी (भारत)'),
        ('ms_Latn_BN',u'Bahasa Melayu (Latin, Brunei)'),
        ('ms_Latn_MY',u'Bahasa Melayu (Latin, Malaysia)'),
        ('ms_Latn_SG',u'Bahasa Melayu (Latin, Singapura)'),
        ('mt_MT',u'Malti (Malta)'),
        ('mua_CM',u'MUNDAŊ (kameruŋ)'),
        ('my_MM',u'ဗမာ (မြန်မာ)'),
        ('naq_NA',u'Khoekhoegowab (Namibiab)'),
        ('nb_NO',u'norsk bokmål (Norge)'),
        ('nd_ZW',u'isiNdebele (Zimbabwe)'),
        ('ne_IN',u'नेपाली (भारत)'),
        ('ne_NP',u'नेपाली (नेपाल)'),
        ('nl_AW',u'Nederlands (Aruba)'),
        ('nl_BE',u'Nederlands (België)'),
        ('nl_CW',u'Nederlands (Curaçao)'),
        ('nl_NL',u'Nederlands (Nederland)'),
        ('nl_SR',u'Nederlands (Suriname)'),
        ('nl_SX',u'Nederlands (Sint-Maarten)'),
        ('nmg_CM',u'Kwasio (Kamerun)'),
        ('nn_NO',u'nynorsk (Noreg)'),
        ('nnh_CM',u'Shwóŋò ngiembɔɔn (Kàmalûm)'),
        ('nr_ZA',u'isiNdebele'),
        ('nso_ZA',u'Sesotho sa Leboa'),
        ('nus_SD',u'Thok Nath (Sudan)'),
        ('nyn_UG',u'Runyankore (Uganda)'),
        ('om_ET',u'Oromoo (Itoophiyaa)'),
        ('om_KE',u'Oromoo (Keeniyaa)'),
        ('or_IN',u'ଓଡ଼ିଆ (ଭାରତ)'),
        ('os_GE',u'ирон (Гуырдзыстон)'),
        ('os_RU',u'ирон (Уӕрӕсе)'),
        ('pa_Arab_PK',u'پنجاب (العربية, پکستان)'),
        ('pa_Guru_IN',u'ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ, ਭਾਰਤ)'),
        ('pl_PL',u'polski (Polska)'),
        ('ps_AF',u'پښتو (افغانستان)'),
        ('pt_AO',u'português (Angola)'),
        ('pt_BR',u'português (Brasil)'),
        ('pt_CV',u'português (Cabo Verde)'),
        ('pt_GW',u'português (Guiné Bissau)'),
        ('pt_MO',u'português (Macau, RAE da China)'),
        ('pt_MZ',u'português (Moçambique)'),
        ('pt_PT',u'português (Portugal)'),
        ('pt_ST',u'português (São Tomé e Príncipe)'),
        ('pt_TL',u'português (Timor-Leste)'),
        ('rm_CH',u'rumantsch (Svizra)'),
        ('rn_BI',u'Ikirundi (Uburundi)'),
        ('ro_MD',u'română (Republica Moldova)'),
        ('ro_RO',u'română (România)'),
        ('rof_TZ',u'Kihorombo (Tanzania)'),
        ('ru_BY',u'русский (Беларусь)'),
        ('ru_KG',u'русский (Киргизия)'),
        ('ru_KZ',u'русский (Казахстан)'),
        ('ru_MD',u'русский (Молдова)'),
        ('ru_RU',u'русский (Россия)'),
        ('ru_UA',u'русский (Украина)'),
        ('rw_RW',u'Kinyarwanda (Rwanda)'),
        ('rwk_TZ',u'Kiruwa (Tanzania)'),
        ('sah_RU',u'саха тыла'),
        ('saq_KE',u'Kisampur (Kenya)'),
        ('sbp_TZ',u'Ishisangu (Tansaniya)'),
        ('se_FI',u'davvisámegiella (Suopma)'),
        ('se_NO',u'davvisámegiella (Norga)'),
        ('seh_MZ',u'sena (Moçambique)'),
        ('ses_ML',u'Koyraboro senni (Maali)'),
        ('sg_CF',u'Sängö (Ködörösêse tî Bêafrîka)'),
        ('shi_Latn_MA',u'tamazight (lmɣrib)'),
        ('shi_Tfng_MA',u'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)'),
        ('si_LK',u'සිංහල (ශ්‍රී ලංකාව)'),
        ('sk_SK',u'slovenčina (Slovensko)'),
        ('sl_SI',u'slovenščina (Slovenija)'),
        ('sn_ZW',u'chiShona (Zimbabwe)'),
        ('so_DJ',u'Soomaali (Jabuuti)'),
        ('so_ET',u'Soomaali (Itoobiya)'),
        ('so_KE',u'Soomaali (Kiiniya)'),
        ('so_SO',u'Soomaali (Soomaaliya)'),
        ('sq_AL',u'shqip (Shqipëria)'),
        ('sq_MK',u'shqip (Maqedoni)'),
        ('sq_XK',u'shqip (Kosovë)'),
        ('sr_Cyrl_BA',u'српски (Ћирилица, Босна и Херцеговина)'),
        ('sr_Cyrl_ME',u'Српски (Ћирилица, Црна Гора)'),
        ('sr_Cyrl_RS',u'Српски (Ћирилица, Србија)'),
        ('sr_Cyrl_XK',u'Српски (Ћирилица, Косово)'),
        ('sr_Latn_BA',u'Srpski (Latinica, Bosna i Hercegovina)'),
        ('sr_Latn_ME',u'Srpski (Latinica, Crna Gora)'),
        ('sr_Latn_RS',u'Srpski (Latinica, Srbija)'),
        ('sr_Latn_XK',u'Srpski (Latinica, Kosovo)'),
        ('ss_SZ',u'Siswati'),
        ('ss_ZA',u'Siswati'),
        ('st_LS',u'Sesotho'),
        ('st_ZA',u'Sesotho'),
        ('sv_AX',u'svenska (Åland)'),
        ('sv_FI',u'svenska (Finland)'),
        ('sv_SE',u'svenska (Sverige)'),
        ('sw_KE',u'Kiswahili (Kenya)'),
        ('sw_TZ',u'Kiswahili (Tanzania)'),
        ('sw_UG',u'Kiswahili (Uganda)'),
        ('swc_CD',u'Kiswahili ya Kongo (Jamhuri ya Kidemokrasia ya Kongo)'),
        ('ta_IN',u'தமிழ் (இந்தியா)'),
        ('ta_LK',u'தமிழ் (இலங்கை)'),
        ('ta_MY',u'தமிழ் (மலேஷியா)'),
        ('ta_SG',u'தமிழ் (சிங்கப்பூர்)'),
        ('te_IN',u'తెలుగు (భారత దేశం)'),
        ('teo_KE',u'Kiteso (Kenia)'),
        ('teo_UG',u'Kiteso (Uganda)'),
        ('tg_Cyrl_TJ',u'Тоҷикӣ (Тоҷикистон)'),
        ('th_TH',u'ไทย (ไทย)'),
        ('ti_ER',u'ትግርኛ (ኤርትራ)'),
        ('ti_ET',u'ትግርኛ (ኢትዮጵያ)'),
        ('tig_ER',u'ትግረ (ኤርትራ)'),
        ('tn_BW',u'Setswana'),
        ('tn_ZA',u'Setswana'),
        ('to_TO',u'lea fakatonga (Tonga)'),
        ('tr_CY',u'Türkçe (Güney Kıbrıs Rum Kesimi)'),
        ('tr_TR',u'Türkçe (Türkiye)'),
        ('ts_ZA',u'Xitsonga'),
        ('twq_NE',u'Tasawaq senni (Nižer)'),
        ('tzm_Latn_MA',u'Tamaziɣt (Meṛṛuk)'),
        ('uk_UA',u'українська (Україна)'),
        ('ur_IN',u'اردو (بھارت)'),
        ('ur_PK',u'اردو (پاکستان)'),
        ('uz_Arab_AF',u'اوزبیک (Араб, افغانستان)'),
        ('uz_Cyrl_UZ',u'Ўзбек (Кирил, Ўзбекистон)'),
        ('uz_Latn_UZ',u'oʻzbekcha (Lotin, Oʻzbekiston)'),
        ('vai_Latn_LR',u'Vai (Laibhiya)'),
        ('vai_Vaii_LR',u'ꕙꔤ (ꕞꔤꔫꕩ)'),
        ('ve_ZA',u'Tshivenḓa'),
        ('vi_VN',u'Tiếng Việt (Việt Nam)'),
        ('vun_TZ',u'Kyivunjo (Tanzania)'),
        ('wae_CH',u'Walser (Schwiz)'),
        ('wal_ET',u'ወላይታቱ (ኢትዮጵያ)'),
        ('xh_ZA',u'isiXhosa'),
        ('xog_UG',u'Olusoga (Yuganda)'),
        ('yav_CM',u'nuasue (Kemelún)'),
        ('yo_NG',u'Èdè Yorùbá (Orílẹ́ède Nàìjíríà)'),
        ('zh_Hans_CN',u'中文 (简体中文, 中国)'),
        ('zh_Hans_HK',u'中文 (简体中文, 中国香港特别行政区)'),
        ('zh_Hans_MO',u'中文 (简体中文, 中国澳门特别行政区)'),
        ('zh_Hans_SG',u'中文 (简体中文, 新加坡)'),
        ('zh_Hant_HK',u'中文 (繁體漢字, 中華人民共和國香港特別行政區)'),
        ('zh_Hant_MO',u'中文 (繁體中文, 中華人民共和國澳門特別行政區)'),
        ('zh_Hant_TW',u'中文 (繁體中文, 台灣)'),
        ('zu_ZA',u'isiZulu (iNingizimu Afrika)'),
    ]

    @classmethod
    def localeFullName(cls,code):
        for key,value in cls.LOCALE:
            if key == code:
                return value

    @classmethod
    def langFullName(cls,code):
        if cls.LANG.has_key(code):
            return I18n.LANG[code]

# class I18n():
#     LANG = {
#         "in":u"Bahasa Indonesia",
#         "ca":u"Català",
#         "cs":u"Čeština",
#         "da":u"Dansk",
#         "de":u"Deutsch",
#         "en_GB":u"English (UK)‎",
#         "en":u"English (US)‎",
#         "es":u"Español",
#         "es_419":u"Español (Latinoamérica)‎",
#         "tl":u"Filipino",
#         "fr":u"Français",
#         "hr":u"Hrvatski",
#         "it":u"Italiano",
#         "lv":u"Latviešu",
#         "lt":u"Lietuvių",
#         "hu":u"Magyar",
#         "nl":u"Nederlands",
#         "no":u"Norsk (bokmål)",
#         "pl":u"Polski",
#         "pt_BR":u"Português (Brasil)‎",
#         "pt_PT":u"Português (Portugal)‎",
#         "ro":u"Română",
#         "sk":u"Slovenčina",
#         "sl":u"slovenščina",
#         "fi":u"Suomi",
#         "sv":u"Svenska",
#         "tr":u"Türkçe",
#         "vi":u"Tiếng Việt",
#         "el":u"Ελληνικά",
#         "ru":u"Русский",
#         "sr":u"Српски",
#         "uk":u"Українська",
#         "bg":u"Български",
#         "iw":u"עברית",
#         "ar":u"العربية",
#         "fa":u"فارسی",
#         "hi":u"हिन्दी",
#         "th":u"ภาษาไทย",
#         "zh_TW":u"中文（繁體）‎",
#         "zh_CN":u"中文（简体）‎",
#         "ja":u"日本語"
#     }
